---
- name: Set up workyard internal server
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install base packages
      apt:
        name: "{{ item}}"
        state: present
      with_items:
        - tmux 
        - vim 
        - tig

    - name: add docker apt key
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80 
        id: 58118E89F3A912897C070ADBF76221572C52609D


    - name: add docker apt repository
      apt_repository:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
        state: present


    - name: add docker packages
      apt:
        name: docker-engine
        update_cache: yes
        state: present

